"""init

Revision ID: 03c991204ea9
Revises: 
Create Date: 2020-02-05 22:17:11.144721

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03c991204ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
            'guilds',
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('prefix', sa.String(), nullable=False),
            sa.Column('soundmaster', sa.BigInteger(), nullable=True),
            sa.Column('soundplayer', sa.BigInteger(), nullable=True),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'sounds',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('played', sa.Integer(), server_default='0', nullable=False),
            sa.Column('stopped', sa.Integer(), server_default='0', nullable=False),
            sa.Column('source', sa.Text(), nullable=False),
            sa.Column('uploader', sa.BigInteger(), nullable=False),
            sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('length', sa.Interval(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE COLLATION case_insensitive (provider = icu, locale = 'und-u-ks-level2', deterministic = false)")
    op.create_table(
            'sound_names',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('sound_id', sa.Integer(), nullable=False),
            sa.Column('guild_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(collation='case_insensitive'), nullable=False),
            sa.Column('is_alias', sa.Boolean(), server_default=sa.text('false'), nullable=False),
            sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['sound_id'], ['sounds.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('sound_id', 'guild_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sound_names')
    op.execute('DROP COLLATION case_insensitive')
    op.drop_table('sounds')
    op.drop_table('guilds')
    # ### end Alembic commands ###
